import { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { ShieldCheck, CreditCard, CheckCircle2, XCircle, ArrowLeft, Lock, Loader2, Sparkles, Building2, RefreshCw } from 'lucide-react';
import { fetchRecoveryCase, simulateDemoPaymentSuccess, simulateDemoPaymentFailure } from '../api';

export default function DemoPayment() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();

  const [loading, setLoading] = useState(true);
  const [caseData, setCaseData] = useState<any>(null);
  const [processing, setProcessing] = useState(false);
  const [paymentStatus, setPaymentStatus] = useState<'idle' | 'success' | 'failed'>('idle');
  const [statusMessage, setStatusMessage] = useState('');
  const [recoveredAmount, setRecoveredAmount] = useState<number>(5000);

  useEffect(() => {
    if (!id) return;
    loadCase();
  }, [id]);

  const loadCase = async () => {
    try {
      setLoading(true);
      const res = await fetchRecoveryCase(id!);
      if (res && !res.error) {
        setCaseData(res);
        setRecoveredAmount(res.amount || res.transactionId?.amount || 5000);
        if (res.status === 'RECOVERED') {
          setPaymentStatus('success');
          setStatusMessage('This payment has already been successfully recovered.');
        }
      }
    } catch (err) {
      console.error('Failed to load case:', err);
    } finally {
      setLoading(false);
    }
  };

  const handlePaySuccess = async () => {
    if (!id) return;
    try {
      setProcessing(true);
      const res = await simulateDemoPaymentSuccess(id);
      if (res && res.actualRecovered) {
        setPaymentStatus('success');
        setRecoveredAmount(res.actualRecovered);
        setStatusMessage(`Payment of ₹${res.actualRecovered.toLocaleString('en-IN')} verified & captured! Webhook processed and revenue credited.`);
      } else {
        setPaymentStatus('success');
        setStatusMessage('Payment captured successfully!');
      }
    } catch (err: any) {
      console.error('Payment error:', err);
      setPaymentStatus('failed');
      setStatusMessage(err.message || 'Payment simulation failed.');
    } finally {
      setProcessing(false);
    }
  };

  const handlePayFailure = async () => {
    if (!id) return;
    try {
      setProcessing(true);
      await simulateDemoPaymentFailure(id);
      setPaymentStatus('failed');
      setStatusMessage('Payment simulation failed at issuer bank. Attempt count incremented.');
    } catch (err: any) {
      setPaymentStatus('failed');
      setStatusMessage(err.message || 'Error simulating payment failure.');
    } finally {
      setProcessing(false);
    }
  };

  if (loading) {
    return (
      <div className="min-h-[80vh] flex flex-col items-center justify-center gap-4">
        <Loader2 className="w-8 h-8 text-primary animate-spin" />
        <p className="text-sm text-gray-400">Loading RevPulse Payment Portal...</p>
      </div>
    );
  }

  const tx = caseData?.transactionId || {};
  const customer = caseData?.customerId || {};
  const amount = caseData?.amount || tx.amount || 5000;
  const txId = tx.transactionIdStr || tx.id || id;

  return (
    <div className="max-h-full py-6 px-4 flex flex-col items-center justify-center">
      {/* Top Banner */}
      <div className="w-full max-w-xl mb-4 flex items-center justify-between">
        <button
          onClick={() => navigate('/cases')}
          className="flex items-center gap-1.5 text-xs text-gray-400 hover:text-white transition-colors"
        >
          <ArrowLeft className="w-3.5 h-3.5" /> Back to Recovery Cases
        </button>
        <div className="flex items-center gap-1.5 text-xs font-semibold px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
          <ShieldCheck className="w-3.5 h-3.5" /> RevPulse Sandbox Checkout
        </div>
      </div>

      {/* Main Payment Card */}
      <div className="w-full max-w-xl bg-surface border border-border rounded-2xl shadow-2xl overflow-hidden backdrop-blur-xl">
        {/* Header */}
        <div className="bg-gradient-to-r from-primary/20 via-cyan-500/10 to-transparent p-6 border-b border-border flex items-center justify-between">
          <div>
            <div className="flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-primary animate-pulse" />
              <h2 className="text-lg font-bold text-white tracking-wide">RevPulse Payment Portal</h2>
            </div>
            <p className="text-xs text-gray-400 mt-0.5">Secure payment recovery session generated by Autonomous Agent</p>
          </div>
          <div className="text-right">
            <span className="text-xs text-gray-500 uppercase tracking-wider block">Payable Amount</span>
            <span className="text-2xl font-black text-emerald-400">₹{amount.toLocaleString('en-IN')}</span>
          </div>
        </div>

        {/* Body */}
        <div className="p-6 space-y-6">
          {paymentStatus === 'success' ? (
            <div className="text-center py-8 space-y-4 animate-in fade-in zoom-in-95 duration-300">
              <div className="w-16 h-16 rounded-full bg-emerald-500/10 border border-emerald-500/30 flex items-center justify-center mx-auto text-emerald-400">
                <CheckCircle2 className="w-10 h-10" />
              </div>
              <div>
                <h3 className="text-xl font-bold text-white">Payment Recovered Successfully!</h3>
                <p className="text-sm text-gray-400 mt-1 max-w-md mx-auto">{statusMessage}</p>
              </div>

              <div className="bg-surfaceHover/50 border border-border/50 rounded-xl p-4 max-w-md mx-auto text-left space-y-2 text-xs">
                <div className="flex justify-between text-gray-400">
                  <span>Recovered Revenue:</span>
                  <span className="font-semibold text-emerald-400">₹{recoveredAmount.toLocaleString('en-IN')}</span>
                </div>
                <div className="flex justify-between text-gray-400">
                  <span>Transaction ID:</span>
                  <span className="font-mono text-gray-200">{txId}</span>
                </div>
                <div className="flex justify-between text-gray-400">
                  <span>Recovery Case Status:</span>
                  <span className="font-semibold text-emerald-400">CLOSED (RECOVERED)</span>
                </div>
                <div className="flex justify-between text-gray-400">
                  <span>Webhook Event:</span>
                  <span className="font-mono text-cyan-400">payment.captured verified</span>
                </div>
              </div>

              <div className="flex items-center justify-center gap-3 pt-4">
                <button
                  onClick={() => navigate('/dashboard')}
                  className="px-5 py-2.5 rounded-xl bg-primary text-white font-semibold text-xs hover:bg-primary/90 transition-colors shadow-lg shadow-primary/20"
                >
                  View Updated Dashboard
                </button>
                <button
                  onClick={() => navigate(`/cases/${id}`)}
                  className="px-5 py-2.5 rounded-xl bg-surfaceHover text-gray-200 font-semibold text-xs hover:bg-surface border border-border transition-colors"
                >
                  View Case Timeline
                </button>
              </div>
            </div>
          ) : (
            <>
              {/* Transaction Context */}
              <div className="grid grid-cols-2 gap-3 bg-surfaceHover/40 p-4 rounded-xl border border-border/60 text-xs">
                <div>
                  <span className="text-gray-500 block mb-0.5">Customer</span>
                  <span className="font-medium text-gray-200">{customer.name || 'Demo Customer'}</span>
                  <span className="text-gray-500 block text-[11px] truncate">{customer.email || 'customer@enterprise.io'}</span>
                </div>
                <div>
                  <span className="text-gray-500 block mb-0.5">Reference ID</span>
                  <span className="font-mono text-gray-300 truncate block">{txId}</span>
                  <span className="text-amber-400 text-[11px] block mt-0.5 font-medium">Initial Failure: {caseData?.failureReason || 'BANK_DECLINE'}</span>
                </div>
              </div>

              {/* Payment Method Selector */}
              <div className="space-y-2">
                <label className="text-xs font-semibold text-gray-300 block">Select Payment Channel</label>
                <div className="grid grid-cols-3 gap-2">
                  <div className="p-3 rounded-xl border border-primary bg-primary/10 flex flex-col items-center justify-center gap-1.5 cursor-pointer text-center">
                    <CreditCard className="w-5 h-5 text-primary" />
                    <span className="text-xs font-medium text-white">Credit/Debit Card</span>
                    <span className="text-[10px] text-primary/80">Instant Capture</span>
                  </div>
                  <div className="p-3 rounded-xl border border-border bg-surfaceHover/30 opacity-70 flex flex-col items-center justify-center gap-1.5 text-center">
                    <Building2 className="w-5 h-5 text-gray-400" />
                    <span className="text-xs font-medium text-gray-300">Net Banking</span>
                    <span className="text-[10px] text-gray-500">Fast Transfer</span>
                  </div>
                  <div className="p-3 rounded-xl border border-border bg-surfaceHover/30 opacity-70 flex flex-col items-center justify-center gap-1.5 text-center">
                    <RefreshCw className="w-5 h-5 text-gray-400" />
                    <span className="text-xs font-medium text-gray-300">UPI Instant</span>
                    <span className="text-[10px] text-gray-500">Auto-Debit</span>
                  </div>
                </div>
              </div>

              {/* Card Simulation details */}
              <div className="space-y-3 bg-surfaceHover/20 p-4 rounded-xl border border-border/40">
                <div>
                  <label className="text-[11px] text-gray-400 block mb-1">Simulated Card Number</label>
                  <input
                    type="text"
                    readOnly
                    value="4111 •••• •••• 1111 (Test VISA Card)"
                    className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-xs font-mono text-gray-300 cursor-not-allowed"
                  />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="text-[11px] text-gray-400 block mb-1">Expiry</label>
                    <input
                      type="text"
                      readOnly
                      value="12 / 28"
                      className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-xs font-mono text-gray-300 cursor-not-allowed"
                    />
                  </div>
                  <div>
                    <label className="text-[11px] text-gray-400 block mb-1">CVV</label>
                    <input
                      type="text"
                      readOnly
                      value="•••"
                      className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-xs font-mono text-gray-300 cursor-not-allowed"
                    />
                  </div>
                </div>
              </div>

              {/* Action Buttons */}
              <div className="space-y-2 pt-2">
                <button
                  id="demo-pay-success-button"
                  onClick={handlePaySuccess}
                  disabled={processing}
                  className="w-full py-3 px-4 rounded-xl bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400 text-white font-bold text-sm shadow-lg shadow-emerald-500/20 transition-all flex items-center justify-center gap-2 disabled:opacity-50"
                >
                  {processing ? (
                    <>
                      <Loader2 className="w-4 h-4 animate-spin" /> Verifying with Bank Gateway...
                    </>
                  ) : (
                    <>
                      <CheckCircle2 className="w-4 h-4" /> Pay ₹{amount.toLocaleString('en-IN')} (Simulate Capture)
                    </>
                  )}
                </button>

                <button
                  id="demo-pay-failure-button"
                  onClick={handlePayFailure}
                  disabled={processing}
                  className="w-full py-2 px-4 rounded-xl bg-surfaceHover hover:bg-danger/10 text-gray-400 hover:text-danger text-xs font-medium border border-border transition-colors flex items-center justify-center gap-1.5 disabled:opacity-50"
                >
                  <XCircle className="w-3.5 h-3.5" /> Simulate Bank Failure (Test Retry Logic)
                </button>
              </div>

              {/* Footer Trust badge */}
              <div className="flex items-center justify-center gap-1.5 text-[11px] text-gray-500 pt-2">
                <Lock className="w-3 h-3" /> 256-Bit Encrypted RevPulse Gateway Session
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
